language: java
sudo: false
addons:
  sonarcloud:
    organization: "fbacchella-github"
    token:
      secure: "XWJ0wVivuMHEgvTPvKaXhC5u7+SZfT/XYDC/YkksoFKQmGn7TO2HuwJq9DK7WOXrI5lJC/VKppcLJqwVVh4t7Sk+lz4VJm1vh1dzYwYRIDPguyTRArmw5XHe58QxFvKGTvtO/1BR7/hYYug+n6I3vU8h8M/El+f7inKwzJZYBqg="
services:
  - elasticsearch
script:
  - mvn clean package
  - mvn surefire:test -Dtest=*.TestZMQ* --debug
jdk:
  - openjdk8
  - openjdk12
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
matrix:
  include:
    - jdk: openjdk11
      script:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml"
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar deploy
      on:
          branch: master
env:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=ERROR"
