version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk
            - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
              environment:
                  discovery.type: single-node
        steps:
            - checkout
            - run: sudo apt-get install openjdk-11-jdk-headless openjdk-8-jdk-headless
            - restore_cache:
                key: loghub-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: loghub-{{ checksum "pom.xml" }}
            - run:
                command: mvn compile
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - run:
                command: mvn resources:testResources compiler:testCompile surefire:test
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
            - run:
                command: mvn install -Dmaven.test.skip=true -Dmaven.main.skip=true
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - store_test_results:
                path: target/surefire-reports
