version: 2
jobs:
    build:
        working_directory: ~/loghub
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache
                key: 
                    - loghub-{{ checksum "pom.xml" }}
                    - loghub-
            - run: mvn dependency:go-offline
            - run: mvn package
            - save_cache:
                paths:
                    - ~/.m2
                key: 
                    - loghub-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
